### ISSUE TITLE
Throws JS error when dropdown list is empty

### ISSUE THREAD

**Issue by DaveFox** [PredixDev/px-typeahead#9] opened 2017-02-10 12:09 UTC
When text is entered that doesn't match any result in a local-candidates array and a user presses the up or down arrow key on the keyboard, the component throws the following error: `Uncaught TypeError: Cannot read property 'classList' of undefined`

**Comment by runn-vermel** [comment] 2017-02-18 00:44
I cannot reproduce this. @DaveFox - which browser/os did this happen on?

**Comment by runn-vermel** [comment] 2017-02-18 00:50
Thanks for issue, @DaveFox, this should be fixed in v0.2.20

**Closed as completed by runn-vermel** 2017-02-18 00:50 UTC
Labels: bug
